services:
  api:
    build:
      context: .
      dockerfile: api/Dockerfile
    command: uv run uvicorn app.main:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - sqs
    develop:
      watch:
        - action: sync
          path: ./api/app
          target: /app/app
        - action: rebuild
          path: ./pyproject.toml

  worker:
    build:
      context: .
      dockerfile: worker/Dockerfile
    command: uv run celery -A app.celery worker --loglevel=info
    env_file:
      - .env
    depends_on:
      - sqs
    develop:
      watch:
        - action: sync
          path: ./worker/app
          target: /app/app
        - action: rebuild
          path: ./pyproject.toml

  sqs:
    build:
      context: .
      dockerfile: sqs/Dockerfile
    command: uv run moto_server -H 0.0.0.0 -p 5000
    ports:
      - "5001:5000"
    env_file:
      - .env
    develop:
      watch:
        - action: rebuild
          path: ./pyproject.toml
