[project]
name = "sqs-mock"
version = "0.1.0"
description = "Local SQS mock service with moto"
requires-python = ">=3.14"
dependencies = [
    "moto[server,sqs]>=5.0.26",
]

[dependency-groups]
dev = [
    "mypy>=1.14.1",
    "ruff>=0.8.6",
]
